namespace OctoHome.Shared.DTOs.Hue
{
    public enum HueRoomClass
    {
        Other = 0,
        LivingRoom = 1,
        Kitchen = 2,
        Dining = 3,
        Bedroom = 4,
        KidsBedroom = 5,
        Bathroom = 6,
        Nursery = 7,
        Recreation = 8,
        Office = 9,
        Gym = 10,
        Hallway = 11,
        Toilet = 12,
        FrontDoor = 13,
        Garage = 14,
        Terrace = 15,
        Garden = 16,
        Driveway = 17,
        Carport = 18,
        TV = 19,
        Home = 20,
        Downstairs = 21,
        Upstairs = 22,
        TopFloor = 23,
        Attic = 24,
        GuestRoom = 25,
        Staircase = 26,
        Lounge = 27,
        ManCave = 28,
        Computer = 29,
        Studio = 30,
        Music = 31,
        Reading = 32,
        Closet = 33,
        Storage = 34,
        LaundryRoom = 35,
        Balcony = 36,
        Porch = 37,
        Barbecue = 38,
        Pool = 39
    }
}